### ISSUE TITLE
Chat fails to start with token id

### ISSUE THREAD

**Issue by xHunter** [crisp-im/crisp-sdk-ios#23]
I've seen the chat failing when it's restoring a chat from a token also session reset seems unreliable, changing user and token keeps showing the previous chat.

**Comment by eliottvincent** [comment]
Hello, could you pease elaborate? Could you send a snippet of your code for restoring with the token?

**Comment by xHunter** [comment]
I'm setting user details when the registered user starts a session (app)
```
CrispSDK.setTokenID(tokenID: user.crispTokenId)
CrispSDK.user.email = user.email
CrispSDK.user.nickname = user.name
```
Then later when the chat is presented `self.present(Crisp.ChatViewController(), animated: true)` if the token id was used in another platform (e.g. Android) the chat displays an alert that it failed to start the chat.

**Comment by gergof** [comment]
I've discovered the same problem and it's still present in the latest release.

What I do:
- Set the token ID
- open the chatbox

What I get:
- Error starting chat

If I don't set the tokenID there's no problem.

**Comment by nesium** [comment]
Hi everyone,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
