### ISSUE TITLE
Thread 1: signal SIGABRT error on real devices

### ISSUE THREAD

**Issue by umair975** [crisp-im/crisp-sdk-ios#24]
both objC and Swift samples are working on simulator but throwing signal SIGABRT error on real device

iphone pro max latest ios version.

another issue faced is on simulator if the chat dialog is minimized it wont receive any new messages or show any indicator.

**Comment by carsonli** [comment]
i'm having the same problem for a real device.  all is good until i present chatviewcontroller

**Comment by baptistejamin** [comment]
Hello!

Do you still have the same issue with the last iOS SDK (1.0.12) ?

**Comment by nesium** [comment]
Hi everyone,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
