### ISSUE TITLE
Crash Store.swift - Line 137

### ISSUE THREAD

**Issue by marian-stanciulica** [crisp-im/crisp-sdk-ios#44]
Hello, I'm using the iOS sdk v1.0.13 and sometimes the app crashes with this stacktrace.
Are there any issues if I call CrispSDK.configure(websiteID: "YOUR_WEBSITE_ID") twice with different website ids? There are any issues if I call it on a background thread?
![Screenshot 2021-05-13 at 11 08 12](https://user-images.githubusercontent.com/11156132/118239621-ac19b680-b4a2-11eb-9375-07aaffbf2a5a.png)

I got it in Xcode just now: **Thread 1: Swift runtime failure: Unexpectedly found nil while implicitly unwrapping an Optional value**

**Comment by nesium** [comment]
Hi there,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!

**Comment by Nesh108** [comment]
Just got a crash on iOS in a prod build with the error:

```
Crisp: Store.send(_:originatingFrom:) + 736
```
