### ISSUE TITLE
Crisp Plugin | Bot | RTL | Arabic options text is out of screen

### ISSUE THREAD

**Issue by mohamedabady** [crisp-im/crisp-sdk-ios#55]
![Simulator Screen Shot - iPhone 12 - 2021-08-24 at 13 26 46](https://user-images.githubusercontent.com/47719144/130609010-cb568f6b-3e70-422d-91a2-e1fa3434962c.png)

when using bot to send automatic replies, option text goes outside screen 

when I select an option options text is aligned to the left not the center

![Simulator Screen Shot - iPhone 12 - 2021-08-24 at 13 32 21](https://user-images.githubusercontent.com/47719144/130609304-bde4753b-89e6-478c-9925-1aa3f14acc1c.png)

**Comment by iTarek** [comment]
Why you ignore this issue?

**Comment by nesium** [comment]
Hi everyone,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
