### ISSUE TITLE
Library not loaded: @rpath/Crisp.framework/Crisp

### ISSUE THREAD

**Issue by amitdizvik2021** [crisp-im/crisp-sdk-ios#64]
dyld: Library not loaded: @rpath/Crisp.framework/Crisp
  Referenced from: /private/var/containers/Bundle/Application/D2707F30-7CFD-4889-8CE7-B12A236D5400/Dolfil.app/Dolfil
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by lucasvercelot** [comment]
It works with the 1.3.1 version of the SDK.

**Comment by nesium** [comment]
I cannot reproduce this with the latest CocoaPods version (1.11.3) and the latest Xcode version (13.3). Tested in an Obj-C only and Swift project.

Which versions are you using and what does your Podfile look like? Can you reproduce this in a small sample project?

**Comment by nesium** [comment]
Hi there,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
