### ISSUE TITLE
Avoid potential dependencies duplication

### ISSUE THREAD

**Issue by pizerg** [crisp-im/crisp-sdk-ios#65]
It would be a good idea to declare third party dependencies into the podspec / Package.swift instead of embedding them into the framework.

That way either Cocoapods or SPM can properly resolve the project dependencies and avoid having duplicates, which in the end can cause app malfunctions and/or crashes since at runtime only one of them will be used.

**Comment by nesium** [comment]
Hi there,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
