### ISSUE TITLE
Mixed support logo when the logo is PNG and contains transparency

### ISSUE THREAD

**Issue by StevenWatremez** [crisp-im/crisp-sdk-ios#73]
For the context we provide a logo for all people in our support. This logo is in PNG and contains transparency for the background.

And we see something strange only on iOS, the default logo is in the background of the PNG logo.

You can see it in the screenshot here :
![ScreenShot](https://user-images.githubusercontent.com/11426754/169529563-d127b22b-a181-4e46-a376-9537c8e7ae34.png)

**Comment by nesium** [comment]
Thanks for the report, Steven! This will be fixed in a future release.

**Comment by StevenWatremez** [comment]
Hi, do you have an idea about the milestone of this fix ? When do you have time to fix this issue ?

**Comment by nesium** [comment]
Hi Steven. Unfortunately I cannot provide you with an ETA for this particular issue since this already being worked on as a part of a bigger release.

In the meantime I would suggest that you use images for the website logo and operator avatars that are flattened on an opaque white background.

**Comment by nesium** [comment]
Hi there,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
