### ISSUE TITLE
RTL close button in wrong direction 

### ISSUE THREAD

**Issue by EssamSoft** [crisp-im/crisp-sdk-ios#77]
The close button should be in the left side in Arabic version 
 
<img src="https://i.ibb.co/7W2zSBZ/Screen-Shot-2022-11-13-at-7-18-05-AM.png"  width="400"   />

**Comment by EssamSoft** [comment]
Any update?

**Comment by nesium** [comment]
Hi @EssamSoft. Can you try with the [latest version](https://github.com/crisp-im/crisp-sdk-ios/releases/tag/2.3.0). I believe this should be fixed.

**Comment by nesium** [comment]
Hi there,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
