### ISSUE TITLE
[iOS] Bot extension: button text answers in User Message Action are not wrapped

### ISSUE THREAD

**Issue by StevenWatremez** [crisp-im/crisp-sdk-ios#78]
We are using the CRISP Bot extension :tête_de_robot: to guide our users to the right service.
On some cases, the Bot proposes multiple choices with a User Message Action to guide him through our services.
We noticed that, on some long propositions, the text is not wrapped.
See below the two photos showing what it looks like on a small iOS device VS an Android.

![Screenshot_20221215-140407](https://user-images.githubusercontent.com/11426754/207874788-5eefac27-a47c-4aa8-a176-ed3ae1e080e0.jpg)

![IMG_5498](https://user-images.githubusercontent.com/11426754/207874881-db10b795-c98a-468d-930f-03797304fa43.PNG)

We can see that on the Androids version, even if it’s a bigger phone, the word email on the second answer is properly wrapped.

SDK version : `1.6.4`

**Comment by nesium** [comment]
Hi there,

It’s been a while since this issue was reported, and we’ve launched a new major version of the Crisp SDK since then. The updates might have resolved the issue you encountered.

We’d appreciate it if you test the latest version to see if the issue persists. Feel free to reopen this issue with more details if needed.

Thanks for your support!
