### ISSUE TITLE
ChatViewController crashes when supporting dark/light mode

### ISSUE THREAD

**Issue by juusokos** [crisp-im/crisp-sdk-ios#85]
The Crisp ChatViewController crashes every time when opened within an app that support Dark/Light mode color theming.

Key to the crash is supporting SwiftUI ligh/dark mode:
1. Have ´Global Accent Color Name´ setting for target in default ´AccentColor´ state
2. Add Colors to Assets
3. Try to open Crisp chat

Here’s a simple isolated example project you can use that replicates the crash.

https://github.com/juusokos/Crisp-theme-crash

**Comment by nesium** [comment]
Hey @juusokos. Thank you for putting together an example project! We'll look into the problem.

**Comment by nesium** [comment]
So, it looks like the crash isn't related to the Crisp SDK at all.

I've noticed that the color property of the AccentColor is set to resolve to `tintColor` but only for light mode which is why this crash doesn't happen in dark mode.

<img width="747" alt="Screenshot 2023-06-22 at 16 17 06" src="https://github.com/crisp-im/crisp-sdk-ios/assets/39174/d5d6e8eb-0427-4d3c-beb5-498a3937c5b7">

If we look at the documentation of [UIColor.tintColor](https://developer.apple.com/documentation/uikit/uiview/1622467-tintcolor), we'll find this:
> A color value that resolves at runtime based on the current tint color of the app or trait hierarchy.

You can even reduce the test case to the following which crashes in light mode:

```swift
struct ContentView: View {
    var body: some View {
      Text("Hello World").foregroundColor(.accentColor)
    }
}
```

What happens is an infinite recursion where when accessing Color.accentColor it tries to resolve to UIColor.tintColor which tries to resolve to Color.accentColor which tries to resolve to… (you get the point).

Here's a part of the stack:
<img width="399" alt="Screenshot 2023-06-22 at 16 27 11" src="https://github.com/crisp-im/crisp-sdk-ios/assets/39174/bbb079ea-782d-41eb-86e6-dbdb8d5864bf">

In any event, you don't have to wrap the `ChatViewController` to use it in Swift but can (and should) use our provided [`ChatView`](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/chatview) for SwiftUI.
